extends SceneTree

const COMBO_RUNTIME := preload("res://scripts/vertical_slice/first_playable_combo_runtime.gd")
const COMBAT_GUIDE := preload("res://scripts/vertical_slice/first_playable_combat_guide.gd")
const COMBAT_FEEDBACK := preload("res://scripts/vertical_slice/first_playable_combat_feedback_runtime.gd")
const MASTER_PLANNER := preload("res://scripts/vertical_slice/first_playable_master_martial_planner.gd")
const MARTIAL_HUD := preload("res://scripts/vertical_slice/first_playable_martial_hud_runtime.gd")
const IDENTITY := preload("res://scripts/vertical_slice/first_playable_character_identity.gd")

func _init() -> void:
	var combo := COMBO_RUNTIME.new() as FirstPlayableComboRuntime
	var signature := combo.presentation_signature()
	assert(bool(signature.get("discrete_attack_buttons", false)))
	assert(signature.get("tai_button") == "F")
	assert(signature.get("ji_button") == "G")
	assert(signature.get("fu_button") == "H")
	assert(float(signature.get("combo_buffer_seconds", 0.0)) >= 0.70)
	assert(bool(signature.get("repeat_button_sequences", false)))
	assert(bool(signature.get("direction_modifiers", false)))
	assert(bool(signature.get("air_attack_modifier", false)))
	assert(bool(signature.get("low_attack_modifier", false)))
	assert(bool(signature.get("reversal_modifier", false)))
	assert(bool(signature.get("legacy_single_attack_unbound", false)))
	assert(not bool(signature.get("dedicated_push_attack", true)))
	assert(bool(signature.get("knockback_is_hit_consequence", false)))
	assert(bool(signature.get("guard_reduces_damage_and_knockback", false)))
	assert(bool(signature.get("dodge_negates_hit", false)))
	assert(bool(signature.get("parry_negates_hit", false)))
	assert(bool(signature.get("confirmed_hit_combo_counter", false)))
	assert(bool(signature.get("martial_code_visible", false)))
	assert(bool(signature.get("flow_energy_visible", false)))
	assert(bool(signature.get("technique_name_visible", false)))
	assert(int(signature.get("elemental_recipes", 0)) == 4)
	assert(not bool(signature.get("dedicated_magic_button", true)))
	assert(float(signature.get("climax_reaction_window_seconds", 0.0)) >= 0.40)
	assert(bool(signature.get("defender_control_during_climax", false)))
	assert(bool(signature.get("blocked_hit_does_not_advance_recipe", false)))
	assert(bool(signature.get("evade_or_parry_breaks_code", false)))
	combo.free()

	var guide := COMBAT_GUIDE.new() as FirstPlayableCombatGuide
	var guide_signature := guide.presentation_signature()
	assert(bool(guide_signature.get("attack_families_visible", false)))
	assert(guide_signature.get("tai_key") == "F")
	assert(guide_signature.get("ji_key") == "G")
	assert(guide_signature.get("fu_key") == "H")
	assert(bool(guide_signature.get("repeat_sequences_visible", false)))
	assert(bool(guide_signature.get("direction_modifiers_visible", false)))
	assert(bool(guide_signature.get("elemental_recipes_visible", false)))
	assert(bool(guide_signature.get("climax_reaction_controls_visible", false)))
	assert(not bool(guide_signature.get("dedicated_magic_button_visible", true)))
	assert(bool(guide_signature.get("full_guide_auto_collapses", false)))
	assert(bool(guide_signature.get("compact_hint_after_intro", false)))
	assert(float(guide_signature.get("full_guide_seconds", 99.0)) <= 8.0)
	guide.free()

	var feedback := COMBAT_FEEDBACK.new()
	var feedback_signature: Dictionary = feedback.presentation_signature()
	assert(bool(feedback_signature.get("impact_feedback_runtime", false)))
	assert(bool(feedback_signature.get("world_space_impact_popups", false)))
	assert(int(feedback_signature.get("popup_budget", 999)) <= 6)
	assert(bool(feedback_signature.get("critical_feedback_priority", false)))
	assert(bool(feedback_signature.get("camera_punch_on_impact", false)))
	assert(bool(feedback_signature.get("feedback_is_visual_only", false)))
	assert(not bool(feedback_signature.get("damage_changes", true)))
	assert(not bool(feedback_signature.get("frame_data_changes", true)))
	assert(not bool(feedback_signature.get("ai_changes", true)))
	feedback.free()

	var planner := MASTER_PLANNER.new()
	var planner_signature: Dictionary = planner.presentation_signature()
	assert(bool(planner_signature.get("master_recipe_planner", false)))
	assert(bool(planner_signature.get("plans_from_confirmed_hits", false)))
	assert(bool(planner_signature.get("recipe_prefix_recovery", false)))
	assert(bool(planner_signature.get("planned_tai_ji_fu_steps", false)))
	assert(float(planner_signature.get("flow_threshold", 0.0)) >= 60.0)
	assert(float(planner_signature.get("climax_telegraph_seconds", 0.0)) >= 0.40)
	assert(bool(planner_signature.get("element_requires_completed_recipe", false)))
	assert(not bool(planner_signature.get("dedicated_push_attack", true)))
	assert(bool(planner_signature.get("player_climax_has_defensive_priority", false)))
	assert(not bool(planner_signature.get("damage_changes", true)))
	assert(not bool(planner_signature.get("attribute_buffs", true)))
	planner.free()

	var martial_hud := MARTIAL_HUD.new()
	var hud_signature: Dictionary = martial_hud.presentation_signature()
	assert(bool(hud_signature.get("compact_martial_strip", false)))
	assert(bool(hud_signature.get("legacy_debug_panel_hidden", false)))
	assert(bool(hud_signature.get("rival_climax_telegraph_visible", false)))
	assert(bool(hud_signature.get("rival_reaction_controls_visible", false)))
	assert(bool(hud_signature.get("single_line_fight_ui", false)))
	assert(not bool(hud_signature.get("site_like_panel", true)))
	assert(not bool(hud_signature.get("logic_changes", true)))
	martial_hud.free()

	var identity := IDENTITY.new() as FirstPlayableCharacterIdentity
	var identity_signature := identity.presentation_signature()
	assert(bool(identity_signature.get("combo_runtime", false)))
	assert(bool(identity_signature.get("master_martial_planner", false)))
	assert(bool(identity_signature.get("martial_hud_runtime", false)))
	assert(bool(identity_signature.get("combat_feedback_runtime", false)))
	identity.free()

	print("FIRST_PLAYABLE_COMBO_COMBAT_CONTRACT_OK")
	quit()

# Tehkné Solutions
