#!/usr/bin/env python3
"""Materialize Lian Wu First Playable LOT01 from the recovered canonical Character Lock.

C64 does not redraw Lian Wu. Existing reviewed families are regenerated by their
approved generators; guard/dodge/hit/ko are deterministic candidates built from
the exact historical Character Lock and remain pending visual review until the
C64 contact sheet is approved.

Tehkné Solutions
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

from lian_wu_canonical_identity import validate_source
from generate_lian_wu_body_hook6 import build_region_masks, build_pose

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError as exc:
    raise SystemExit("C64_LOT01=BLOCKED missing dependency Pillow") from exc

SIGNATURE = "Tehkné Solutions"
CANVAS = (1024, 1024)
ALPHA_THRESHOLD = 3
NEUTRAL_REL = Path("assets/characters/lian_wu/character_lock/lian_wu_neutral.png")
STANCE_REL = Path("assets/characters/lian_wu/character_lock/lian_wu_combat_stance.png")
NEUTRAL_FILE_SHA = "0e435757b5c8a114f3ba91653f79bc86db51ee9cf3bfb74c529efed5d4ff7ab5"
STANCE_FILE_SHA = "c8e6cd1feece7c2a54cf2279085c2a4bb33338dd6a3dcb3e4d5a2402b537631c"
CANONICAL_RGBA_SHA = "0bedec17308acd2c7b392f2c989cf97238908aa4f18b73371aa67c741eb6030b"
CANONICAL_BOUNDS = (325, 70, 720, 970)
TARGET_REL = Path("assets/tgap/pack_01_lian_wu/first_playable_lot_01")

EXISTING_GENERATORS = [
    "tools/generate_lian_wu_idle6.py",
    "tools/generate_lian_wu_run8.py",
    "tools/generate_lian_wu_jump_start4.py",
    "tools/generate_lian_wu_jump_loop3.py",
    "tools/generate_lian_wu_fall3.py",
    "tools/generate_lian_wu_body_hook6.py",
]

ANIMATION_SOURCES = {
    "idle": ("assets/pack_01_characters/lian_wu/frames/idle", 8.0, True),
    "run": ("assets/pack_01_characters/lian_wu/frames/run", 12.0, True),
    "jump_start": ("assets/pack_01_characters/lian_wu/frames/jump_start", 12.0, False),
    "airborne": ("assets/pack_01_characters/lian_wu/frames/jump_loop", 10.0, True),
    "fall": ("assets/pack_01_characters/lian_wu/frames/fall", 12.0, False),
    "attack_light": ("assets/pack_01_characters/lian_wu/frames/attacks/ji_body_hook", 10.0, False),
    "guard": ("assets/pack_01_characters/lian_wu/frames/c64/guard", 6.0, True),
    "dodge": ("assets/pack_01_characters/lian_wu/frames/c64/dodge", 14.0, False),
    "hit": ("assets/pack_01_characters/lian_wu/frames/c64/hit", 12.0, False),
    "ko": ("assets/pack_01_characters/lian_wu/frames/c64/ko", 8.0, False),
}
REQUIRED = tuple(ANIMATION_SOURCES.keys())


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def alpha_bounds(image: Image.Image) -> tuple[int, int, int, int]:
    alpha = image.convert("RGBA").getchannel("A")
    return alpha.point(lambda v: 255 if v >= ALPHA_THRESHOLD else 0).getbbox() or (0, 0, 0, 0)


def offset(layer: Image.Image, dx: int, dy: int) -> Image.Image:
    out = Image.new("RGBA", layer.size, (0, 0, 0, 0))
    out.alpha_composite(layer, (int(dx), int(dy)))
    return out


def align_baseline(image: Image.Image, baseline: int) -> Image.Image:
    bounds = alpha_bounds(image)
    if bounds == (0, 0, 0, 0):
        raise ValueError("empty_alpha_after_transform")
    dy = baseline - (bounds[3] - 1)
    return offset(image, 0, dy) if dy else image


def whole_pose(source: Image.Image, source_bounds, angle: float, dx: int = 0) -> Image.Image:
    x0, y0, x1, y1 = source_bounds
    pivot = (int(round((x0 + x1) * 0.5)), int(round(y0 + (y1 - y0) * 0.62)))
    rotated = source.rotate(
        angle,
        resample=Image.Resampling.NEAREST,
        center=pivot,
        expand=False,
        fillcolor=(0, 0, 0, 0),
    )
    posed = offset(rotated, dx, 0) if dx else rotated
    return align_baseline(posed, source_bounds[3] - 1)


def assert_frame(frame: Image.Image, label: str, baseline: int, grounded: bool = True) -> tuple[int, int, int, int]:
    if frame.size != CANVAS:
        raise ValueError(f"{label}:canvas={frame.size}")
    bounds = alpha_bounds(frame)
    if bounds == (0, 0, 0, 0):
        raise ValueError(f"{label}:empty_alpha")
    if bounds[0] <= 0 or bounds[1] <= 0 or bounds[2] >= CANVAS[0] or bounds[3] >= CANVAS[1]:
        raise ValueError(f"{label}:canvas_clip bounds={bounds}")
    if grounded and bounds[3] - 1 != baseline:
        raise ValueError(f"{label}:baseline={bounds[3]-1} expected={baseline}")
    return bounds


def save_family(repo: Path, name: str, frames: list[Image.Image], prefix: str, baseline: int) -> list[dict]:
    folder = repo / "assets/pack_01_characters/lian_wu/frames/c64" / name
    if folder.exists():
        shutil.rmtree(folder)
    folder.mkdir(parents=True, exist_ok=True)
    rows = []
    for index, frame in enumerate(frames, start=1):
        bounds = assert_frame(frame, f"{name}:{index}", baseline)
        path = folder / f"char_lian_wu__{prefix}__f{index:02d}.png"
        frame.save(path, format="PNG", optimize=False, compress_level=9)
        rows.append({
            "index": index,
            "path": path.relative_to(repo).as_posix(),
            "sha256": sha256(path),
            "alpha_bounds": list(bounds),
            "baseline_y": bounds[3] - 1,
        })
    if len({row["sha256"] for row in rows}) != len(rows):
        raise ValueError(f"{name}:duplicate_frames")
    return rows


def articulated(source: Image.Image, bounds, masks, **preset) -> Image.Image:
    return build_pose(source, bounds, masks, preset)


def generate_c64_families(repo: Path) -> dict:
    neutral_path = repo / NEUTRAL_REL
    stance_path = repo / STANCE_REL
    identity = validate_source(neutral_path)
    if identity["file_sha256"] != NEUTRAL_FILE_SHA or identity["decoded_rgba_sha256"] != CANONICAL_RGBA_SHA:
        raise ValueError("neutral_identity_not_exact_historical")
    if sha256(stance_path) != STANCE_FILE_SHA:
        raise ValueError("combat_stance_hash_mismatch")

    neutral = Image.open(neutral_path).convert("RGBA")
    stance = Image.open(stance_path).convert("RGBA")
    bounds = alpha_bounds(neutral)
    if bounds != CANONICAL_BOUNDS:
        raise ValueError(f"neutral_bounds={bounds} expected={CANONICAL_BOUNDS}")
    baseline = bounds[3] - 1
    masks = build_region_masks(neutral.size, bounds)

    # Guard stays tied to the exact recovered combat stance. It is a stable hold.
    guard = [align_baseline(stance, baseline)]

    # Dodge uses the same regional compositor already validated by Body Hook.
    # The feet remain on the canonical baseline while torso/arms/pelvis create an
    # evasive slip rather than rotating the entire character like a paper cutout.
    dodge = [
        articulated(neutral, bounds, masks,
            torso_rot=-1.5, torso_dx=-2, torso_dy=0, pelvis_dx=-3, pelvis_dy=0, legs_dx=-2,
            back_rot=5.0, back_dx=2, back_dy=0, front_rot=-7.0, front_dx=-2, front_dy=0),
        articulated(neutral, bounds, masks,
            torso_rot=-4.0, torso_dx=-6, torso_dy=0, pelvis_dx=-8, pelvis_dy=0, legs_dx=-6,
            back_rot=11.0, back_dx=4, back_dy=-1, front_rot=-14.0, front_dx=-5, front_dy=0),
        articulated(neutral, bounds, masks,
            torso_rot=-7.0, torso_dx=-10, torso_dy=-1, pelvis_dx=-12, pelvis_dy=0, legs_dx=-9,
            back_rot=17.0, back_dx=6, back_dy=-2, front_rot=-20.0, front_dx=-7, front_dy=-1),
        articulated(neutral, bounds, masks,
            torso_rot=-3.0, torso_dx=-5, torso_dy=0, pelvis_dx=-6, pelvis_dy=0, legs_dx=-4,
            back_rot=8.0, back_dx=3, back_dy=0, front_rot=-10.0, front_dx=-3, front_dy=0),
        neutral.copy(),
    ]

    # Hit reaction is also regionally articulated: torso and arms recoil while the
    # stance keeps its grounding, then the exact historical neutral is restored.
    hit = [
        articulated(neutral, bounds, masks,
            torso_rot=3.0, torso_dx=4, torso_dy=0, pelvis_dx=2, pelvis_dy=0, legs_dx=0,
            back_rot=-7.0, back_dx=-2, back_dy=0, front_rot=8.0, front_dx=4, front_dy=-1),
        articulated(neutral, bounds, masks,
            torso_rot=7.0, torso_dx=8, torso_dy=-1, pelvis_dx=4, pelvis_dy=0, legs_dx=1,
            back_rot=-13.0, back_dx=-4, back_dy=-1, front_rot=16.0, front_dx=8, front_dy=-2),
        articulated(neutral, bounds, masks,
            torso_rot=2.0, torso_dx=3, torso_dy=0, pelvis_dx=1, pelvis_dy=0, legs_dx=0,
            back_rot=-4.0, back_dx=-1, back_dy=0, front_rot=5.0, front_dx=3, front_dy=0),
        neutral.copy(),
    ]

    # KO is the one state where whole-body rotation is semantically correct: the
    # fighter progressively collapses to the floor while keeping canvas/baseline gates.
    ko = [
        whole_pose(neutral, bounds, 12.0, 4),
        whole_pose(neutral, bounds, 30.0, 11),
        whole_pose(neutral, bounds, 52.0, 17),
        whole_pose(neutral, bounds, 72.0, 21),
        whole_pose(neutral, bounds, 90.0, 24),
    ]

    families = {
        "guard": save_family(repo, "guard", guard, "guard", baseline),
        "dodge": save_family(repo, "dodge", dodge, "dodge", baseline),
        "hit": save_family(repo, "hit", hit, "hit", baseline),
        "ko": save_family(repo, "ko", ko, "ko", baseline),
    }

    # Exact idle handoffs are byte-preserved; Pillow may not re-encode the historical
    # PNG identically even when decoded pixels are equal.
    for family_name in ("dodge", "hit"):
        handoff = repo / families[family_name][-1]["path"]
        shutil.copyfile(neutral_path, handoff)
        with Image.open(handoff) as opened:
            handoff_bounds = assert_frame(opened.convert("RGBA"), f"{family_name}:handoff", baseline)
        families[family_name][-1].update({
            "sha256": sha256(handoff),
            "alpha_bounds": list(handoff_bounds),
            "baseline_y": handoff_bounds[3] - 1,
        })
        if len({row["sha256"] for row in families[family_name]}) != len(families[family_name]):
            raise ValueError(f"{family_name}:duplicate_frames_after_exact_handoff")
        if families[family_name][-1]["sha256"] != NEUTRAL_FILE_SHA:
            raise ValueError(f"{family_name}_neutral_handoff_hash")

    metadata = {
        "schema": "tehkne/taijifu-c64-lian-first-playable-families/v1",
        "signature": SIGNATURE,
        "status": "candidate_pending_contact_sheet_review",
        "character_id": "lian_wu",
        "source": {
            "neutral": NEUTRAL_REL.as_posix(),
            "neutral_sha256": NEUTRAL_FILE_SHA,
            "neutral_decoded_rgba_sha256": CANONICAL_RGBA_SHA,
            "combat_stance": STANCE_REL.as_posix(),
            "combat_stance_sha256": STANCE_FILE_SHA,
            "alpha_bounds": list(bounds),
            "baseline_y": baseline,
        },
        "families": families,
        "generation_policy": {
            "redraw": False,
            "global_scale": False,
            "identity_mutation": False,
            "regional_articulation_source": "generate_lian_wu_body_hook6.build_pose",
            "nearest_neighbor_rotation": True,
            "baseline_preserved": True,
            "exact_neutral_handoff": ["dodge", "hit"],
            "visual_review_required_before_repo_binary_promotion": True,
        },
    }
    meta = repo / "assets/pack_01_characters/lian_wu/metadata/c64_first_playable_families.json"
    meta.parent.mkdir(parents=True, exist_ok=True)
    meta.write_text(json.dumps(metadata, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return metadata


def run_existing_generators(repo: Path) -> None:
    for relative in EXISTING_GENERATORS:
        command = [sys.executable, str(repo / relative), "--repo-root", str(repo)]
        print("C64_GENERATOR_RUN", relative)
        result = subprocess.run(command, cwd=repo, text=True)
        if result.returncode != 0:
            raise RuntimeError(f"generator_failed={relative} rc={result.returncode}")


def collect_source_frames(repo: Path, source_dir: str) -> list[Path]:
    frames = sorted((repo / source_dir).glob("*.png"))
    if not frames:
        raise ValueError(f"no_frames={source_dir}")
    return frames


def write_spriteframes(target: Path, animation_files: dict[str, list[Path]], specs: dict[str, tuple[float, bool]]) -> None:
    resources: list[str] = []
    ids: dict[Path, int] = {}
    ext_id = 1
    for name in REQUIRED:
        for frame in animation_files[name]:
            ids[frame] = ext_id
            resources.append(
                f'[ext_resource type="Texture2D" path="res://{frame.as_posix()}" id="{ext_id}"]'
            )
            ext_id += 1
    animations = []
    for name in REQUIRED:
        fps, loop = specs[name]
        rows = ", ".join(
            '{"duration": 1.0, "texture": ExtResource("%d")}' % ids[path]
            for path in animation_files[name]
        )
        animations.append(
            '{"frames": [%s], "loop": %s, "name": &"%s", "speed": %.3f}'
            % (rows, "true" if loop else "false", name, fps)
        )
    text = "\n".join([
        f'[gd_resource type="SpriteFrames" load_steps={ext_id} format=3]',
        "",
        *resources,
        "",
        "[resource]",
        "animations = [%s]" % ",\n".join(animations),
        "",
    ])
    target.write_text(text, encoding="utf-8")


def build_contact_sheet(repo: Path, target: Path, animation_files: dict[str, list[Path]]) -> None:
    thumb = 112
    label_w = 150
    gap = 8
    max_frames = max(len(v) for v in animation_files.values())
    width = label_w + max_frames * (thumb + gap) + gap
    height = len(REQUIRED) * (thumb + 28) + 20
    sheet = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(sheet)
    font = ImageFont.load_default()
    for row, name in enumerate(REQUIRED):
        y = 10 + row * (thumb + 28)
        draw.text((8, y + 45), name, fill="black", font=font)
        for col, path in enumerate(animation_files[name]):
            image = Image.open(repo / path).convert("RGBA")
            crop = image.crop(alpha_bounds(image))
            crop.thumbnail((thumb, thumb), Image.Resampling.NEAREST)
            tile = Image.new("RGBA", (thumb, thumb), (240, 240, 240, 255))
            tile.alpha_composite(crop, ((thumb - crop.width) // 2, thumb - crop.height))
            sheet.paste(tile.convert("RGB"), (label_w + col * (thumb + gap), y))
            draw.text((label_w + col * (thumb + gap) + 2, y + thumb + 2), f"f{col+1:02d}", fill="black", font=font)
    sheet.save(target, format="PNG", compress_level=9)


def materialize(repo: Path, c64_meta: dict) -> dict:
    target = repo / TARGET_REL
    if target.exists():
        shutil.rmtree(target)
    (target / "animations").mkdir(parents=True, exist_ok=True)

    animation_files: dict[str, list[Path]] = {}
    specs: dict[str, tuple[float, bool]] = {}
    for name in REQUIRED:
        source_dir, fps, loop = ANIMATION_SOURCES[name]
        sources = collect_source_frames(repo, source_dir)
        destination = target / "animations" / name
        destination.mkdir(parents=True, exist_ok=True)
        copied = []
        for index, source in enumerate(sources, start=1):
            out = destination / f"char_lian_wu__{name}__f{index:02d}.png"
            shutil.copyfile(source, out)
            copied.append(out.relative_to(repo))
        animation_files[name] = copied
        specs[name] = (fps, loop)

    resource = target / "lian_wu_first_playable_frames.tres"
    write_spriteframes(resource, animation_files, specs)

    runtime = {
        "schema": "tehkne/taijifu-first-playable-runtime-map/v1",
        "signature": SIGNATURE,
        "animations": {
            name: {
                "path": f"animations/{name}",
                "fps": specs[name][0],
                "loop": specs[name][1],
                "frames": len(animation_files[name]),
            }
            for name in REQUIRED
        },
    }
    manifest = {
        "schema": "tehkne/taijifu-first-playable-lot/v1",
        "signature": SIGNATURE,
        "lot_id": "pack_01_lian_wu_first_playable_lot_01",
        "stage": "C64",
        "status": "candidate_pending_contact_sheet_review",
        "character_id": "lian_wu",
        "source_character_lock_sha256": NEUTRAL_FILE_SHA,
        "source_character_lock_rgba_sha256": CANONICAL_RGBA_SHA,
        "required_animations": list(REQUIRED),
        "animation_count": len(REQUIRED),
        "frame_count": sum(len(v) for v in animation_files.values()),
        "spriteframes": resource.relative_to(repo).as_posix(),
        "c64_families_metadata": "assets/pack_01_characters/lian_wu/metadata/c64_first_playable_families.json",
    }
    approval = {
        "schema": "tehkne/taijifu-first-playable-approval/v1",
        "signature": SIGNATURE,
        "status": "candidate_pending_visual_review",
        "technical_generation": "pass",
        "binary_promotion_allowed": False,
        "required_review_artifact": "c64-lian-first-playable-contact-sheet.png",
    }
    (target / "manifest.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    (target / "runtime-map.json").write_text(json.dumps(runtime, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    (target / "approval.json").write_text(json.dumps(approval, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    checks = []
    for path in sorted(target.rglob("*")):
        if path.is_file() and path.name != "checksums.sha256":
            checks.append(f"{sha256(path)}  {path.relative_to(target).as_posix()}")
    (target / "checksums.sha256").write_text("\n".join(checks) + "\n", encoding="utf-8")

    contact = repo / "c64-lian-first-playable-contact-sheet.png"
    build_contact_sheet(repo, contact, animation_files)

    report = {
        "schema": "tehkne/taijifu-c64-lot01-materialization-report/v1",
        "signature": SIGNATURE,
        "status": "candidate_pending_contact_sheet_review",
        "required_animation_count": len(REQUIRED),
        "frame_count": manifest["frame_count"],
        "animations": {name: len(animation_files[name]) for name in REQUIRED},
        "spriteframes": resource.relative_to(repo).as_posix(),
        "contact_sheet": contact.name,
        "source_exact_historical": True,
        "c64_new_families": {name: len(c64_meta["families"][name]) for name in ("guard", "dodge", "hit", "ko")},
    }
    report_path = repo / "c64-lian-first-playable-report.json"
    report_path.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return report


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    args = parser.parse_args()
    repo = Path(args.repo_root).resolve()
    try:
        run_existing_generators(repo)
        c64_meta = generate_c64_families(repo)
        report = materialize(repo, c64_meta)
    except (OSError, ValueError, RuntimeError) as exc:
        print(f"C64_LOT01=BLOCKED {exc}")
        return 2
    print("C64_LOT01_MATERIALIZATION=PASS")
    print(f"animations={report['required_animation_count']}/10")
    print(f"frames={report['frame_count']}")
    print(f"spriteframes={report['spriteframes']}")
    print("visual_review=PENDING")
    print(f"SIGNATURE={SIGNATURE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
