param([string]$RepoRoot='.',[string]$GodotExe='')
$ErrorActionPreference='Stop'; $RepoRoot=(Resolve-Path $RepoRoot).Path
function Resolve-Godot([string]$Explicit){ if($Explicit -and (Test-Path $Explicit)){return (Resolve-Path $Explicit).Path}; foreach($n in @('godot','godot4','godot.exe','godot4.exe')){$c=Get-Command $n -ErrorAction SilentlyContinue; if($c -and $c.Source){return $c.Source}}; foreach($root in @("$env:LOCALAPPDATA\Microsoft\WinGet\Packages","$env:LOCALAPPDATA\Programs","$env:USERPROFILE\Downloads","$env:ProgramFiles","C:\Godot","C:\tools")|Where-Object{$_ -and(Test-Path $_)}){$f=Get-ChildItem $root -File -Filter 'Godot*.exe' -Recurse -ErrorAction SilentlyContinue|Where-Object{$_.Name -notmatch 'console'}|Sort-Object LastWriteTime -Descending|Select-Object -First 1; if($f){return $f.FullName}}; return $null }
$runner=Join-Path $RepoRoot 'tools\GENERATE-VM02-A7-FALL3.ps1'; if(-not(Test-Path $runner)){Write-Host 'VM02_A7_FALL3_BENCH=BLOCKED_GENERATOR_RUNNER_MISSING'; exit 2}
powershell -ExecutionPolicy Bypass -File $runner -RepoRoot $RepoRoot; if($LASTEXITCODE -ne 0){Write-Host 'VM02_A7_FALL3_BENCH=BLOCKED_GENERATION'; exit $LASTEXITCODE}
$godot=Resolve-Godot $GodotExe; if(-not $godot){Write-Host 'VM02_A7_GODOT_RESOLVE=BLOCKED'; exit 3}; Write-Host 'VM02_A7_GODOT_RESOLVE=PASS'; Write-Host "GODOT_EXE=$godot"
$artifactDir=Join-Path $RepoRoot 'artifacts\vm02-a7'; New-Item -ItemType Directory -Force -Path $artifactDir|Out-Null; $output=Join-Path $artifactDir 'lian-wu-fall3-bench-1920x1080.png'; Remove-Item $output -Force -ErrorAction SilentlyContinue
$logDir=Join-Path $RepoRoot '.godot\vm02-a7'; New-Item -ItemType Directory -Force -Path $logDir|Out-Null; $stdout=Join-Path $logDir 'fall3-bench.stdout.log'; $stderr=Join-Path $logDir 'fall3-bench.stderr.log'; Remove-Item $stdout,$stderr -Force -ErrorAction SilentlyContinue
$args=@('--path',$RepoRoot,'--resolution','1920x1080','res://scenes/visual/lian_wu_fall3_visual_bench.tscn','--','--capture-and-quit')
$p=Start-Process -FilePath $godot -ArgumentList $args -WorkingDirectory $RepoRoot -Wait -PassThru -RedirectStandardOutput $stdout -RedirectStandardError $stderr
$combined=@(); if(Test-Path $stdout){$combined+=Get-Content $stdout}; if(Test-Path $stderr){$combined+=Get-Content $stderr}; foreach($line in $combined){Write-Host $line}
$fatal=@($combined|Where-Object{$_ -match 'SCRIPT ERROR|Parse Error|Compile Error|Failed to load script|VM02_A7_FALL3_BENCH_RUNTIME=BLOCKED'}); if($p.ExitCode -ne 0 -or $fatal.Count -gt 0 -or -not(Test-Path $output)){Write-Host 'VM02_A7_FALL3_BENCH=BLOCKED'; exit 4}
Add-Type -AssemblyName System.Drawing; $img=[System.Drawing.Image]::FromFile($output); try{if($img.Width -ne 1920 -or $img.Height -ne 1080){Write-Host 'VM02_A7_FALL3_BENCH=BLOCKED_SIZE'; exit 5}}finally{$img.Dispose()}
$hash=(Get-FileHash $output -Algorithm SHA256).Hash.ToLowerInvariant(); Write-Host 'VM02_A7_FALL3_BENCH=PASS'; Write-Host "VM02_A7_FALL3_BENCH_OUTPUT=$output"; Write-Host "VM02_A7_FALL3_BENCH_SHA256=$hash"; Write-Host 'VM02_A7_FALL3_PROMOTION=PENDING_VISUAL_REVIEW'
